
clean:
	rm -f thread_create thread_create_simple_args thread_create_with_return_args

thread_create:
	zig build-exe thread_create.zig
	rm -f thread_create.o

thread_create_simple_args:
	zig build-exe thread_create_simple_args.zig
	rm -f thread_create_simple_args.o


thread_create_with_return_args:
	zig build-exe thread_create_with_return_args.zig
	rm -f thread_create_with_return_args.o

