
clean:
	rm -f p1 p2 p3 p4
	rm -f p1.o p2.o p3.o p4.o
	rm -f p4.output output.txt


p1:
	zig build-exe p1.zig 
	rm -f p1.o


p2:
	zig build-exe p2.zig 
	rm -f p2.o

p3:
	zig build-exe p3.zig 
	rm -f p3.o


p4:
	zig build-exe p4.zig 
	rm -f p4.o



